using System;
using System.Collections.Generic;

namespace AppMiTaller.Web.BE
{
    [Serializable]
    public class CitasBE
    {
        public Int32 nid_pais { get; set; }
        public Int32 nid_cita { get; set; }
        public Int32 nid_cliente { get; set; }
        public Int32 nid_taller { get; set; }
        public Int32 nid_contacto { get; set; }
        public Int32 nid_vehiculo { get; set; }
        public string fl_origen { get; set; }
        public Int32 qt_km_inicial { get; set; }
        public DateTime fe_atencion { get; set; }
        public Int32 dia_prog { get; set; }
        public string tx_glos { get; set; }
        public string tx_glosa_atencion { get; set; }
        public string nu_placa { get; set; }
        public Int32 nu_anio_vehiculo { get; set; }
        public string co_tipo_vehiculo { get; set; }
        public Int32 nid_propietario { get; set; }
        public Int32 nid_marca { get; set; }
        public Int32 nid_modelo { get; set; }
        public Int32 nid_estado { get; set; }
        public Int32 nid_usuario { get; set; }
        public Int32 nid_servicio { get; set; }
        public string cod_reserva_cita { get; set; }
        public DateTime fe_prog { get; set; }
        public string ho_prog { get; set; }
        public string nu_celular { get; set; }
        public string tx_observacion { get; set; }
        public string no_taller { get; set; }
        public string no_asesor { get; set; }
        public string ho_inicio { get; set; }
        public string ho_fin { get; set; }
        public string no_estado { get; set; }
        public Int32 nid_tipo_servicio { get; set; }
        public string no_servicio { get; set; }
        public Int32 nid_ubica { get; set; }
        public string no_ubica { get; set; }
        public string di_ubica { get; set; }
        public string no_direccion_t { get; set; }
        public string tx_mapa_taller { get; set; }
        public string tx_url_taller { get; set; }
        public string no_distrito { get; set; }
        public string nu_telefono { get; set; }
        public string nu_telefono_t { get; set; }
        public string no_modelo { get; set; }
        public string no_marca { get; set; }
        public string no_nombre { get; set; }
        public string no_ape_paterno { get; set; }
        public string no_ape_materno { get; set; }
        public Int32 co_tipo_doc { get; set; }
        public string co_tipo_documento { get; set; }
        public string nu_documento { get; set; }
        public string no_email { get; set; }
        public string no_email_trabajo { get; set; }
        public string no_email_alter { get; set; }
        public string no_correo { get; set; }
        public string no_correo_trabajo { get; set; }
        public string no_correo_alter { get; set; }
        public string nu_tel_fijo { get; set; }
        public string nu_tel_movil { get; set; }
        public Int32 co_estado_cita { get; set; }
        public Int32 nu_estado { get; set; }
        public string no_estado_cita { get; set; }
        public string fl_quick_service { get; set; }
        public string qt_intervalo_atenc { get; set; }
        public string no_dias_validos { get; set; }
        public Int32 dd_atencion { get; set; }
        public string ho_taller_ini { get; set; }
        public string ho_taller_fin { get; set; }
        public Int32 nid_regCita { get; set; }
        public string fl_datos_pend { get; set; }
        public string no_pais { get; set; }
        public string coddpto { get; set; }
        public string codprov { get; set; }
        public string coddist { get; set; }
        public string fi_acceso { get; set; }
        public string ff_acceso { get; set; }
        public string no_tipo_servicio { get; set; }
        public Int32 co_intervalo_atenc { get; set; }
        public Int32 nid_taller_empresa { get; set; }
        public string no_banco { get; set; }
        public string nu_cuenta { get; set; }
        public string nu_callcenter { get; set; }
        public string no_correo_callcenter { get; set; }
        public string fl_activo { get; set; }
        public string no_empresa { get; set; }
        public string co_intervalo { get; set; }
        public Int32 nu_intervalo { get; set; }
        public Int32 nid_empresa { get; set; }
        
        public string no_direccion { get; set; }
        public string fecha_atencion { get; set; }
        public string no_cliente { get; set; }
        public string nomdpto { get; set; }
        public string nomprov { get; set; }
        public string nomdist { get; set; }
        public string nu_telefono_a { get; set; }
        public string nu_telefono_c { get; set; }
        public string nu_celular_c { get; set; }
        public string ho_inicio_t { get; set; }
        public string ho_fin_t { get; set; }
        public string fl_control { get; set; }
        public Int32 nid_asesor { get; set; }
        public string horario_asesor { get; set; }
        public string no_correo_a { get; set; }
        public string ho_rango1 { get; set; }
        public string ho_rango2 { get; set; }
        public string ho_rango3 { get; set; }
        public Nullable<Int32> qt_cola_espera { get; set; }
        public string server_mapth { get; set; }
        public string tipo_email { get; set; }
        public Int32 tipo_cita { get; set; }
        public string no_correo_asesor { get; set; }
        public string fecha_prog { get; set; }
        public Int32 dd_atencion_t { get; set; }
        public Int32 dd_atencion_r { get; set; }
        public string co_estado { get; set; }
        public Nullable<Int32> qt_capacidad_a { get; set; }
        public Nullable<Int32> qt_capacidad_t { get; set; }
        public Nullable<Int32> qt_cantidad_t { get; set; }
        public Nullable<Int32> qt_cantidad_a { get; set; }
        public Nullable<Int32> qt_citas_t { get; set; }
        public Nullable<Int32> qt_citas_a { get; set; }
        public Nullable<Int32> qt_capacidad_m { get; set; }
        public Nullable<Int32> qt_citas_m { get; set; }
        public Nullable<Int32> qt_cantidad_m { get; set; }
        public Nullable<Int32> nid_dia_exceptuado_a { get; set; }
        public Nullable<Int32> nid_dia_exceptuado_t { get; set; }
        public string ho_inicio_c { get; set; }
        public string ho_fin_c { get; set; }
        public string fl_nota { get; set; }
        public string fl_taxi { get; set; }
        public string co_valoracion { get; set; }
        public string tx_legal { get; set; }
        public string tx_alternativo_01 { get; set; }
        public string tx_alternativo_02 { get; set; }
        public int nid_tbl_texto_legales { get; set; }
        public string fl_tipo_texto_legal { get; set; }
        public string co_origencita { get; set; }
        public String no_nombreqr { get; set; }
        public String no_color_exterior { get; set; }
    }
    [Serializable]
    public class CitasBEList : List<CitasBE> { }
}